name: Docker Build Custom
# Manually trigger a docker image build
on:
  workflow_dispatch:
    inputs:
      tags:
        description: Comma seperated list of tags, defaults to the branch/commit name.
        type: string
        default: ${{ gtihub.ref }}
      base_tag:
        description: Which tag to use for the base image (digiserve/service-cli)
        default: develop
        type: choice
        options: [ master, develop ]
jobs:
  call-docker-build:
    uses: digi-serve/.github/.github/docker-build.yml@master
    with:
      base_tag: ${{ inputs.base_tag }}
      tags: ${{ inputs.tags }}
    secrets: inherit
    